export const THEMES = [
  {
    id: 'ocean',
    name: 'Océan',
    description: 'Moderne & professionnel',
    preview: {
      navbar: '#ffffff',
      navbarBorder: '#e5e7eb',
      navbarText: '#111827',
      heroFrom: '#1d4ed8',
      heroTo: '#2563eb',
      primary: '#2563EB',
      bg: '#F8FAFC',
      surface: '#ffffff',
      text: '#111827',
      muted: '#6b7280',
    },
  },
  {
    id: 'minuit',
    name: 'Minuit Doré',
    description: 'Luxe & premium',
    preview: {
      navbar: '#1E1C2E',
      navbarBorder: '#37354F',
      navbarText: '#FFFFFE',
      heroFrom: '#0F0E17',
      heroTo: '#2D1B69',
      primary: '#D4AF37',
      bg: '#0F0E17',
      surface: '#1E1C2E',
      text: '#FFFFFE',
      muted: '#9ca3af',
    },
  },
  {
    id: 'foret',
    name: 'Forêt',
    description: 'Naturel & bio',
    preview: {
      navbar: '#ffffff',
      navbarBorder: '#bbf7d0',
      navbarText: '#14532d',
      heroFrom: '#14532d',
      heroTo: '#16a34a',
      primary: '#16A34A',
      bg: '#F0FDF4',
      surface: '#ffffff',
      text: '#14532d',
      muted: '#64748b',
    },
  },
  {
    id: 'feu',
    name: 'Feu',
    description: 'Bold & urbain',
    preview: {
      navbar: '#18181B',
      navbarBorder: '#3f3f46',
      navbarText: '#FAFAFA',
      heroFrom: '#09090B',
      heroTo: '#3f0f0f',
      primary: '#EF4444',
      bg: '#09090B',
      surface: '#18181B',
      text: '#FAFAFA',
      muted: '#a1a1aa',
    },
  },
]
